# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [24]:
import numpy as np



### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [22]:
import numpy as np
a = np.arange(1, 16).reshape(3, 5)
print(a)
print(a.ndim) 
print(a.shape)
print(a.size)
print(a.dtype)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
15
int32


In [28]:
Z=array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]],[[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(Z)
print(Z.shape)
print(Z.ndim)
print(Z.size)
print(Z.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
3
27
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [30]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [31]:
print(B-C)
print(B*C)
print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [51]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
expontiate = np.exp(B)
print(expontiate)
min_value = B.min()
print("Minimum value in the matrix B:", min_value)
min_value_per_row = np.min(B, axis=1)
print("minimum value in each row:", min_value_per_row)
min_value_per_column = np.min(B, axis=0)
print("Minimum value in each columns:", min_value_per_column)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Minimum value in the matrix B: 1
minimum value in each row: [1 4 7]
Minimum value in each columns: [1 2 3]


In [3]:
import numpy as np
A = np.arange(1, 16).reshape(3, 5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
A[1, :]


array([ 6,  7,  8,  9, 10])

[2 3 4]


**Answer:**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [50]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [11]:
for row in A:
   for element in row: 
        print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [24]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print(b)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


answer: We have an one dimensional array contains of 30 elements; in reshaping process we make a 3 dimensional array which has two layers. Numpy uses -1 to automatically count the number of the elements in an intact way. we have 30 elements, 3 rows(0,1,2) and 5 columns(0,1,2,3,4) which calculated from the number of elements (30) divided to 6. and 6 is the multiplication of 2 and 3.


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [62]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])

print(m1 + m2)



[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [63]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [26]:
A = np.arange(1, 5).reshape(2,2)
print(A)


b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [90]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])
x = np.linalg.solve(A, b)
print(x)

[ 8.  2. -1.]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [91]:
def add_mult_matrices(matrix1, matrix2, operation):
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both inputs must be NumPy arrays (matrices).")
    
    if operation not in ('add', 'multiply'):
        raise ValueError("The operation must be 'add' or 'multiply'.")
    
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition.")
        result = matrix1 + matrix2
    else:  # operation == 'multiply'
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix for multiplication.")
        result = np.dot(matrix1, matrix2)
    
    return result

# Example usage:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix addition
result_add = add_mult_matrices(matrix_a, matrix_b, 'add')
print("Matrix Addition Result:")
print(result_add)

# Matrix multiplication
result_mult = add_mult_matrices(matrix_a, matrix_b, 'multiply')
print("\nMatrix Multiplication Result:")
print(result_mult)

Matrix Addition Result:
[[ 6  8]
 [10 12]]

Matrix Multiplication Result:
[[19 22]
 [43 50]]


**Chap2. Question 2**

In [39]:
import numpy as np

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = np.dot(A, B)
AC = np.dot(A, C)
print(AB)
print(AC)
are_equal = np.array_equal(AB, AC)
not_equal = not np.array_equal(B, C)
print("AB:")
print(AB)
print("AC:")
print(AC)
print("AB is equal to AC:", are_equal)
print("B is not equal to C:", not_equal)

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
AB:
[[ 4  7]
 [ 8 14]]
AC:
[[ 4  7]
 [ 8 14]]
AB is equal to AC: True
B is not equal to C: True


**Chap2. Question 3**

In [43]:
import numpy as np

A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

AD = np.dot(A, D)
DA = np.dot(D, A)
print("AD:")
print(AD)

print("DA:")
print(DA)

AD:
[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
DA:
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [58]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2, 1],
              [2, 4, 1],
              [3, 6, 2]], dtype=float)  # Convert to float for division

# Perform Gaussian elimination to get the RREF
def compute_rref(matrix):
    M = matrix.copy()
    n_rows, n_cols = M.shape
    pivot_columns = []
    lead = 0

    for r in range(n_rows):
        if lead >= n_cols:
            break
        i = r
        while M[i, lead] == 0:
            i += 1
            if i == n_rows:
                i = r
                lead += 1
                if n_cols == lead:
                    break
        M[[i, r]] = M[[r, i]]
        if M[r, lead] != 0:
            M[r] /= M[r, lead]
            for i in range(n_rows):
                if i != r:
                    M[i] -= M[i, lead] * M[r]
        pivot_columns.append(lead)
        lead += 1

    return M, pivot_columns

rref, pivot_columns = compute_rref(A)

# Replace "-0" with "0" in the RREF matrix
rref[rref == -0] = 0

# Print the formatted RREF matrix
print("Reduced Row Echelon Form (RREF) of A:")
print(rref)


print("Pivot Columns:")
print(pivot_columns)



Reduced Row Echelon Form (RREF) of A:
[[1. 2. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Pivot Columns:
[0, 2]


**Chap 6. Question 1**

In [64]:
import numpy as np

matrix1 = np.array([[5, 6], [4, 5]], dtype=float)
matrix2 = np.array([[6, 4], [3, 3]], dtype=float)

inverse1 = np.linalg.inv(matrix1)
inverse2 = np.linalg.inv(matrix2)

print("Inverse of Matrix 1:")
print(inverse1)

print("Inverse of Matrix 2:")
print(inverse2)



Inverse of Matrix 1:
[[ 5. -6.]
 [-4.  5.]]
Inverse of Matrix 2:
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [67]:
I don\t know which excercise exactly!


**Chap10. Question 1 a)**

In [72]:
import numpy as np
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]], dtype=float)
b = np.array([-7, 5, 2], dtype=float)

n = len(b)
x = np.zeros(n)

for k in range(n - 1):
    for i in range(k + 1, n):
        factor = A[i, k] / A[k, k]
        for j in range(k, n):
            A[i, j] -= factor * A[k, j]
        b[i] -= factor * b[k]

x[n - 1] = b[n - 1] / A[n - 1, n - 1]
for k in range(n - 2, -1, -1):
    x[k] = (b[k] - np.sum(A[k, k + 1:] * x[k + 1:])) / A[k, k]
print("Solution:")
print(x)


Solution:
[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [73]:
import numpy as np
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]], dtype=float)
b = np.array([1, -1, 1], dtype=float)


n = len(b)
x = np.zeros(n)

for k in range(n - 1):
    for i in range(k + 1, n):
        factor = A[i, k] / A[k, k]
        for j in range(k, n):
            A[i, j] -= factor * A[k, j]
        b[i] -= factor * b[k]

x[n - 1] = b[n - 1] / A[n - 1, n - 1]
for k in range(n - 2, -1, -1):
    x[k] = (b[k] - np.sum(A[k, k + 1:] * x[k + 1:])) / A[k, k]

print("Solution:")
print(x)


Solution:
[ 8.  2. -1.]


**Chap 12. Question 1**

In [71]:
import numpy as np
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]], dtype=float)
A_inverse = np.linalg.inv(A)

print("Inverse of the matrix:")
print(A_inverse)


Inverse of the matrix:
[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [19]:
v1 = np.arange(4)
v2 = v1[1:4]
print(v1)
print(v2)


[0 1 2 3]
[1 2 3]


In [75]:
import numpy as np
v1 = np.arange(4)
v2 = v1[1:4]

# Check if v1 and v2 are views or copies
print(v1.base is not None)
print(v2.base is not None)


False
True


In [20]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [21]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  1   2 123]
